# Generated by Django 4.1.5 on 2023-04-13 15:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('nom', models.CharField(blank=True, default='', max_length=50)),
                ('prenoms', models.CharField(blank=True, default='', max_length=100)),
                ('username', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='./field360App/media/')),
                ('numero', models.CharField(default='', max_length=20, unique=True)),
                ('date_naissance', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('lieu_naissance', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('numero_piece', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('date_expiration', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('piece_recto', models.ImageField(blank=True, null=True, upload_to='./field360App/media/')),
                ('piece_verso', models.ImageField(blank=True, null=True, upload_to='./field360App/media/')),
                ('account_validated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('client_logo', models.ImageField(blank=True, null=True, upload_to='./field360App/media/')),
                ('client_name', models.CharField(max_length=20, unique=True)),
                ('client_status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id_country', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('country_prefixe', models.CharField(max_length=10)),
                ('flag', models.ImageField(default='', upload_to='./field360App/media/')),
                ('number_of_clients', models.IntegerField(default=0, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id_dashboard', models.AutoField(primary_key=True, serialize=False)),
                ('dashboard_name', models.CharField(max_length=255)),
                ('refresh_frequency', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id_domaine', models.AutoField(primary_key=True, serialize=False)),
                ('domaine_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id_education', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=100)),
                ('level_number', models.IntegerField()),
                ('id_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.countries')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('exam_order', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id_industry', models.AutoField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=100, unique=True)),
                ('industry_status', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id_media', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='./field360App/media/')),
                ('remark', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Privilege',
                'verbose_name_plural': 'Privileges',
                'db_table': 'privilege',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product_picture', models.ImageField(blank=True, null=True, upload_to='./field360App/media/')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('product_commission', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.clients')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.countries')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizExamen',
            fields=[
                ('id_quiz_examen', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_question_name', models.CharField(max_length=100)),
                ('quiz_question_points', models.IntegerField(default=0)),
                ('quiz_question_type', models.CharField(max_length=100)),
                ('quiz_question_media', models.ImageField(default='', upload_to='./field360App/media/')),
                ('quiz_description', models.TextField()),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exam')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSection',
            fields=[
                ('id_quiz_section', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_question_name', models.CharField(max_length=100)),
                ('quiz_question_points', models.IntegerField(default=0)),
                ('quiz_question_type', models.CharField(max_length=100)),
                ('quiz_question_media', models.ImageField(blank=True, null=True, upload_to='./field360App/media/')),
                ('quiz_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TokenPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=40, unique=True)),
                ('pin', models.CharField(max_length=4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserScoreQuiz',
            fields=[
                ('id_user_score', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombredepoints', models.IntegerField()),
                ('results', models.BooleanField(default=False)),
                ('id_quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.quizsection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserScoreExam',
            fields=[
                ('id_user_score', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombredepoints', models.IntegerField()),
                ('results', models.BooleanField(default=False)),
                ('id_exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersClient',
            fields=[
                ('id_userclient', models.AutoField(primary_key=True, serialize=False)),
                ('userclient_email', models.CharField(max_length=100, unique=True)),
                ('userclient_identifiant', models.CharField(max_length=100, unique=True)),
                ('userclient_name', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='./field360App/media/')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.clients')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.countries')),
                ('privilege', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.privilege')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id_user_quiz', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.CharField(max_length=100)),
                ('answer', models.BooleanField(default=False)),
                ('id_quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.quizsection')),
            ],
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id_user_exam', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.CharField(max_length=100)),
                ('answer', models.BooleanField(default=False)),
                ('id_quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.quizexamen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeID',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('id_name', models.CharField(max_length=100)),
                ('number_typeid', models.IntegerField(default=0)),
                ('id_country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.countries')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id_training', models.AutoField(primary_key=True, serialize=False)),
                ('training_name', models.CharField(max_length=100)),
                ('training_onBoarding', models.CharField(max_length=100)),
                ('training_min_score', models.CharField(max_length=100)),
                ('training_description', models.TextField()),
                ('training_mode', models.CharField(default='', max_length=100)),
                ('training_statut', models.CharField(default='', max_length=100)),
                ('training_category', models.CharField(default='', max_length=100)),
                ('countrie_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.countries')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clients')),
                ('produit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id_target', models.AutoField(primary_key=True, serialize=False)),
                ('target_zone', models.CharField(max_length=100, unique=True)),
                ('target_month', models.CharField(max_length=100, unique=True)),
                ('target_moderm', models.DecimalField(decimal_places=3, max_digits=8)),
                ('target_routeurs', models.DecimalField(decimal_places=3, max_digits=8)),
                ('target_airtelmoney', models.DecimalField(decimal_places=3, max_digits=8)),
                ('target_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.clients')),
                ('target_countrie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.countries')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('sections_name', models.CharField(max_length=100)),
                ('id_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.training')),
                ('sections_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quizsection',
            name='id_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sections'),
        ),
        migrations.AddField(
            model_name='quizsection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id_pos', models.AutoField(primary_key=True, serialize=False)),
                ('pos_indication', models.IntegerField(default='')),
                ('pos_name', models.CharField(max_length=250, unique=True)),
                ('pos_long', models.FloatField()),
                ('pos_lat', models.FloatField()),
                ('pos_active', models.IntegerField()),
                ('numb_pos', models.IntegerField(default=0)),
                ('pos_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.clients')),
                ('pos_countrie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.countries')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PisteAudite',
            fields=[
                ('id_piste_audit', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.FileField(upload_to='')),
                ('details_actions', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_piste_audit_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id_locality', models.AutoField(primary_key=True, serialize=False)),
                ('locality_name', models.CharField(max_length=100)),
                ('id_country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('nom', models.CharField(blank=True, default='', max_length=50)),
                ('prenoms', models.CharField(blank=True, default='', max_length=100)),
                ('username', models.CharField(default='', max_length=20, unique=True)),
                ('date_naissance', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('lieu_naissance', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('numero_piece', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('date_expiration', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('isNomOk', models.BooleanField(default=False)),
                ('isPrenomOk', models.BooleanField(default=False)),
                ('isTypepPieceOk', models.BooleanField(default=False)),
                ('isDateNaissanceOk', models.BooleanField(default=False)),
                ('isLieuNaissanceOk', models.BooleanField(default=False)),
                ('isTypePieceOk', models.BooleanField(default=False)),
                ('isNumeroPieceOk', models.BooleanField(default=False)),
                ('isDateExpirationOk', models.BooleanField(default=False)),
                ('isPhotoSelfieOk', models.BooleanField(default=False)),
                ('isPieceRectoOk', models.BooleanField(default=False)),
                ('isPieceVersoOk', models.BooleanField(default=False)),
                ('isAllok', models.BooleanField(default=False)),
                ('clients_kyc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.clients')),
                ('country_kyc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.countries')),
                ('kycAgentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kyc_agent_id', to=settings.AUTH_USER_MODEL)),
                ('localite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kyc_localite_id', to='api.locality')),
                ('niveau_education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kyc_niveau_education_id', to='api.educationlevel')),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kyc_pays_id', to='api.countries')),
                ('photo_selfie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_photo_selfie_of_user', to='api.media')),
                ('piece_recto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_piece_recto_of_user', to='api.media')),
                ('piece_verso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_piece_vers_of_user', to='api.media')),
                ('type_piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kyc_type_piece_id', to='api.typeid')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_agent_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Footsoldiers',
            fields=[
                ('id_footsoldiers', models.AutoField(primary_key=True, serialize=False)),
                ('footsoldiers_phonenumber', models.CharField(max_length=100, unique=True)),
                ('footsoldiers_fullname', models.CharField(max_length=100, unique=True)),
                ('footsoldiers_zone', models.URLField()),
                ('footsoldiers_picture', models.ImageField(blank=True, null=True, upload_to='./field360App/media/')),
                ('footsoldiers_clients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.clients')),
                ('footsoldiers_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.countries')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='id_training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.training'),
        ),
        migrations.AddField(
            model_name='exam',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clients',
            name='client_industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.industry'),
        ),
        migrations.AddField(
            model_name='clients',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.countries'),
        ),
        migrations.AddField(
            model_name='clients',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id_chapter', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_order', models.CharField(max_length=100)),
                ('chapter_name', models.CharField(max_length=100)),
                ('chapter_description', models.TextField()),
                ('id_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sections')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswersSection',
            fields=[
                ('id_answer_section', models.AutoField(primary_key=True, serialize=False)),
                ('answer_label', models.TextField()),
                ('answer_correct', models.BooleanField(default=False)),
                ('id_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_QuizSection_id', to='api.quizsection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswersExamen',
            fields=[
                ('id_answer_examen', models.AutoField(primary_key=True, serialize=False)),
                ('answer_label', models.TextField()),
                ('answer_correct', models.BooleanField(default=False)),
                ('id_quiz_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quizexamen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pays_id', to='api.countries'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='localite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='localite_id', to='api.locality'),
        ),
        migrations.AddField(
            model_name='user',
            name='niveau_education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='niveau_education_id', to='api.educationlevel'),
        ),
        migrations.AddField(
            model_name='user',
            name='privilege',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.privilege'),
        ),
        migrations.AddField(
            model_name='user',
            name='the_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.clients'),
        ),
        migrations.AddField(
            model_name='user',
            name='type_piece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_piece_id', to='api.typeid'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
