# Generated by Django 4.1.5 on 2023-04-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='number_of_clients',
            new_name='numbers_of_clients',
        ),
    ]
