# Generated by Django 4.1.5 on 2023-04-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_countries_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='level_number',
            field=models.IntegerField(default=0),
        ),
    ]
