# Generated by Django 4.1.5 on 2023-04-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_educationlevel_level_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_onBoarding',
            field=models.BooleanField(default=True),
        ),
    ]
