# Generated by Django 4.1.5 on 2023-04-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_training_training_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_min_score',
            field=models.FloatField(default=0),
        ),
    ]
